import type { PageAlertState } from '@/hooks/usePageAlert';
import type {
  ActiveFilterChipDescriptor,
  DraftFilterOverrides,
  ReportDateRange,
  ReportFilterSnapshot,
} from '@/modules/mis/services/filters';
import type { RegisterDateFilterColumn } from '@/sql/trhcalls/query';
import type { CallCorpusStore } from '@/modules/mis/services/data-store';

export type ReportFiltersContextValue = {
  search: string;
  setSearch: (v: string) => void;
  debouncedSearch: string;
  pincodeSearch: string;
  setPincodeSearch: (v: string) => void;
  debouncedPincodeSearch: string;
  isSearchDebouncing: boolean;
  flushSearchDebounce: () => void;
  dateRange: ReportDateRange;
  setDateRange: (v: ReportDateRange) => void;
  agingAsOf: string;
  setAgingAsOf: (v: string) => void;
  dateFilterColumn: RegisterDateFilterColumn;
  setDateFilterColumn: (v: RegisterDateFilterColumn) => void;
  dateFilterColumnOptions: ReadonlyArray<{ value: RegisterDateFilterColumn; label: string }>;
  selectedOfficeIds: string[];
  setSelectedOfficeIds: (v: string[]) => void;
  selectedCallTypes: string[];
  setSelectedCallTypes: (v: string[]) => void;
  selectedStatus: string[];
  setSelectedStatus: (v: string[]) => void;
  priorityFilter: string[];
  setPriorityFilter: (v: string[]) => void;
  portalFilter: string[];
  setPortalFilter: (v: string[]) => void;
  repairFilter: string[];
  setRepairFilter: (v: string[]) => void;
  selectedState: string[];
  setSelectedState: (v: string[]) => void;
  selectedCity: string[];
  setSelectedCity: (v: string[]) => void;
  selectedRegion: string[];
  setSelectedRegion: (v: string[]) => void;
  selectedAccount: string[];
  setSelectedAccount: (v: string[]) => void;
  selectedBranch: string[];
  setSelectedBranch: (v: string[]) => void;
  selectedFranchisee: string[];
  setSelectedFranchisee: (v: string[]) => void;
  selectedTechnician: string[];
  setSelectedTechnician: (v: string[]) => void;
  offices: any[];
  callTypes: string[];
  statesList: any[];
  setStatesList: (v: any[]) => void;
  citiesList: any[];
  setCitiesList: (v: any[]) => void;
  regionsList: Array<{ vname: string; call_count?: number }>;
  setRegionsList: (v: Array<{ vname: string; call_count?: number }>) => void;
  accountsList: Array<{ vname: string; call_count?: number }>;
  setAccountsList: (v: Array<{ vname: string; call_count?: number }>) => void;
  techniciansList: any[];
  setTechniciansList: (v: any[]) => void;
  showOfficeDropdown: boolean;
  setShowOfficeDropdown: (v: boolean) => void;
  tempSelectedOfficeIds: string[];
  setTempSelectedOfficeIds: (v: string[]) => void;
  officeSearch: string;
  setOfficeSearch: (v: string) => void;
  handleStatesChange: (values: string[]) => void;
  handleBranchesChange: (values: string[]) => void;
  handleCitiesChange: (values: string[]) => void;
  clearAllFilters: () => void;
  isAnyFilterActive: boolean;
  callTypeOptions: { value: string; label: string }[];
  stateOptions: { value: string; label: string }[];
  cityOptions: { value: string; label: string }[];
  regionOptions: { value: string; label: string }[];
  accountOptions: { value: string; label: string }[];
  technicianOptions: { value: string; label: string }[];
  branchesList: Array<{ ncode: string; vcompanyname: string; call_count?: number }>;
  franchiseesList: Array<{ ncode: string; vcompanyname: string; call_count?: number }>;
  setBranchesList: (v: Array<{ ncode: string; vcompanyname: string; call_count?: number }>) => void;
  setFranchiseesList: (v: Array<{ ncode: string; vcompanyname: string; call_count?: number }>) => void;
  distributionCalls: any[];
  distributionBranches: any[];
  distributionLoading: boolean;
  fetchDistributionData: (force?: boolean) => Promise<void>;
  ensureSharedCallsLoaded: (force?: boolean) => Promise<void>;
  ensureCorpusLoaded: (opts?: { force?: boolean; silent?: boolean }) => Promise<void>;
  rehydrateDistributionFromCache: () => void;
  runBackgroundSync: (opts?: { showToast?: boolean }) => Promise<void>;
  lastSyncedAt: Date | null;
  syncInProgress: boolean;
  corpusStatus: CallCorpusStore['status'];
  corpusLoading: boolean;
  corpusTick: number;
  corpusTruncated: boolean;
  corpusCallCount: number;
  syncCascadeOptionsFromCalls: (calls: any[]) => void;
  resourcesLoaded: boolean;
  appliedFilters: ReportFilterSnapshot | null;
  appliedRevision: number;
  applyFilters: (overrides?: DraftFilterOverrides) => ReportFilterSnapshot;
  applyFilterSnapshot: (snapshot: ReportFilterSnapshot) => void;
  removeActiveFilterChip: (chip: ActiveFilterChipDescriptor) => void;
  getAppliedFiltersSnapshot: () => ReportFilterSnapshot | null;
  hasPendingFilterChanges: boolean;
  getAppliedDateStrings: () => { startDateStr: string; endDateStr: string } | null;
  getAppliedDateFilterColumn: () => RegisterDateFilterColumn | null;
  prefsReady: boolean;
  reportBanner: PageAlertState;
  setReportError: (message: string) => void;
  setReportWarning: (message: string) => void;
  clearReportBanner: () => void;
  refreshDelta: { added: number; updated: number } | null;
  clearRefreshDelta: () => void;
};
