/** Human-readable labels for activity log UI. */
export const ACTION_LABELS: Record<string, string> = {
  'auth.sign_in.success': 'Signed in',
  'auth.sign_in.failure': 'Sign-in failed',
  'auth.sign_out': 'Signed out',
  'auth.token.invalid': 'Invalid token',
  'auth.access.denied': 'Access denied',
  'auth.password_reset.request': 'Requested password reset',
  'auth.password_reset.complete': 'Changed password',
  'admin.user.create': 'Created user',
  'admin.user.update': 'Updated user',
  'admin.user.delete': 'Deleted user',
  'admin.user.password_reset': 'Reset user password',
  'admin.role.create': 'Created role',
  'admin.role.update': 'Updated role',
  'admin.role.delete': 'Deleted role',
  'admin.mis_email_org_settings.update': 'Updated MIS email org settings',
  'admin.mis_email_routing.create': 'Created MIS email routing rule',
  'admin.mis_email_routing.update': 'Updated MIS email routing rule',
  'admin.mis_email_routing.delete': 'Deleted MIS email routing rule',
  'admin.major_repair_recipient.create': 'Created major-repair alert recipient',
  'admin.major_repair_recipient.update': 'Updated major-repair alert recipient',
  'admin.major_repair_recipient.delete': 'Deleted major-repair alert recipient',
  'admin.mis_email.test': 'Sent MIS email test',
  'profile.update': 'Updated profile',
  'profile.mis_email.update': 'Updated MIS email preferences',
  'profile.mis_email.send': 'Sent MIS email digest',
  'import.mis_client.upload.start': 'Started MIS client import',
  'import.mis_client.upload': 'Finished MIS client import',
  'import.mis_client.delete': 'Deleted MIS client import',
  'import.mis_client.download': 'Downloaded MIS client import',
  'import.mis_client.source.create': 'Created MIS import source',
  'import.mis_client.source.update': 'Updated MIS import source',
  'profile.avatar.upload': 'Uploaded profile avatar',
  'register.flag.set': 'Set call flag',
  'register.comment.create': 'Added call comment',
  'admin.call_register.visible_clients.update': 'Updated Call Register visible accounts',
  'report.export.start': 'Started report export',
  'report.export.complete': 'Exported report',
  'report.export.cancelled': 'Cancelled report export',
  'report.export.failure': 'Report export failed',
  'sync.manual.start': 'Started manual sync',
  'sync.manual.complete': 'Completed manual sync',
  'sync.manual.failure': 'Manual sync failed',
};

export function actionLabelFor(eventType: string): string {
  return ACTION_LABELS[eventType] ?? eventType;
}
