/** Columns selected for register list/bulk/export queries (avoids SELECT h.*). */
import {
  HOT_OFFICE_JOINS_SQL,
  HOT_RESOLVED_REGION_SQL,
} from '@/lib/read-model/queries/hot-region';

export { HOT_OFFICE_JOINS_SQL };

export const REGISTER_HOT_COLUMNS = [
  'h.ncode',
  'h.vtrnno',
  'h.vcclid',
  'h.nofficeid',
  'h.nengineer',
  'h.office_under',
  'h.franchisee_code',
  'h.party_name',
  'h.branch_name',
  'h.franchisee_name',
  'h.pincode',
  'h.city',
  'h.state',
  `${HOT_RESOLVED_REGION_SQL} AS region`,
  'h.account',
  'h.item_name',
  'h.serial',
  'h.wco',
  'h.engineer_name',
  'h.call_type',
  'h.complaint',
  'h.status_label',
  'h.status_bucket',
  'h.solve_remarks',
  'h.contact_person',
  'h.phone',
  'h.address',
  'h.has_visit',
  'h.is_major',
  'h.is_part_pending',
  'h.branch_headcount',
  'h.logged_at',
  'h.solved_at',
  'h.bsolved',
  'h.bfastclose',
  'h.ncancelreason',
  'h.lat',
  'h.lng',
].join(',\n    ');

/** Minimal hot-table projection for register CSV export (fewer columns, faster I/O). */
export const REGISTER_EXPORT_HOT_COLUMNS = [
  'h.ncode',
  'h.vtrnno',
  'h.vcclid',
  'h.party_name',
  'h.branch_name',
  `${HOT_RESOLVED_REGION_SQL} AS region`,
  'h.account',
  'h.franchisee_name',
  'h.pincode',
  'h.item_name',
  'h.serial',
  'h.wco',
  'h.engineer_name',
  'h.call_type',
  'h.is_major',
  'h.complaint',
  'h.status_label',
  'h.logged_at',
  'h.solved_at',
  'h.solve_remarks',
  'h.contact_person',
  'h.phone',
  'h.address',
  'h.bsolved',
  'h.bfastclose',
  'h.ncancelreason',
].join(',\n    ');

/** Minimal columns for distribution idle-assignee / audit scope computations. */
export const DISTRIBUTION_COMPACT_COLUMNS = [
  'h.ncode',
  'h.nengineer',
  'h.engineer_name',
  'h.franchisee_code',
  'h.franchisee_name',
  'h.branch_name',
  'h.pincode',
  'h.city',
  'h.state',
  'h.status_bucket',
  'h.status_label',
  'h.bsolved',
  'h.bfastclose',
  'h.ncancelreason',
  'h.lat',
  'h.lng',
  'h.logged_at',
].join(',\n    ');

export const REGISTER_BULK_MAX_ROWS = 100_000;
