#!/usr/bin/env bash
# Point Supabase GoTrue (forgot password) at the same SMTP as MIS reports.
# On VPS:
#   bash scripts/vps-hosting/sync-gotrue-smtp.sh
# From PC:
#   npm run gotrue:sync-smtp:vps
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/mis-smtp-env.sh"

SUPABASE_DIR="${SUPABASE_DIR:-/opt/supabase/docker}"
MAIL_DOMAIN="${MAIL_DOMAIN:-wrl-fsm.cloud}"

set_env() {
  local key="$1"
  local val="$2"
  grep -v "^${key}=" "${SUPABASE_DIR}/.env" > "${SUPABASE_DIR}/.env.tmp" 2>/dev/null || true
  mv "${SUPABASE_DIR}/.env.tmp" "${SUPABASE_DIR}/.env"
  printf '%s=%s\n' "$key" "$val" >> "${SUPABASE_DIR}/.env"
}

sync_gotrue_smtp() {
  if [[ ! -f "${SUPABASE_DIR}/.env" ]]; then
    echo "FATAL: missing ${SUPABASE_DIR}/.env — run repair-supabase-env.sh first" >&2
    exit 1
  fi

  load_mis_smtp_vars

  local gotrue_host admin_email sender_name
  gotrue_host="$(resolve_gotrue_smtp_host "$SMTP_HOST")"
  admin_email="$(parse_smtp_admin_email "$SMTP_FROM")"
  sender_name="$(parse_smtp_sender_name "$SMTP_FROM")"

  echo "==> GoTrue SMTP (same as MIS reports)"
  echo "    From: ${sender_name} <${admin_email}>"
  echo "    Relay: ${gotrue_host}:${SMTP_PORT} (MIS uses ${SMTP_HOST}:${SMTP_PORT})"
  if [[ -n "${SMTP_USER:-}" ]]; then
    echo "    Auth: ${SMTP_USER}"
  else
    echo "    Auth: none (local Postfix)"
  fi

  set_env SMTP_ADMIN_EMAIL "$admin_email"
  set_env SMTP_HOST "$gotrue_host"
  set_env SMTP_PORT "$SMTP_PORT"
  set_env SMTP_USER "${SMTP_USER:-}"
  set_env SMTP_PASS "${SMTP_PASS:-}"
  set_env SMTP_SENDER_NAME "$sender_name"

  local override_dst="${SUPABASE_DIR}/docker-compose.override.yml"
  cat > "$override_dst" <<EOF
# Generated by sync-gotrue-smtp.sh — same Postfix relay as MIS reports.
services:
  auth:
    environment:
      GOTRUE_SMTP_HOST: ${gotrue_host}
      GOTRUE_SMTP_PORT: ${SMTP_PORT}
      GOTRUE_SMTP_USER: ""
      GOTRUE_SMTP_PASS: ""
      GOTRUE_SMTP_ADMIN_EMAIL: ${admin_email}
      GOTRUE_SMTP_SENDER_NAME: ${sender_name}
EOF
  echo "==> Installed ${override_dst} (gateway ${gotrue_host})"

  if ! grep -q 'docker-compose.override.yml' "${SUPABASE_DIR}/.env" 2>/dev/null; then
    local compose_file
    compose_file="$(grep '^COMPOSE_FILE=' "${SUPABASE_DIR}/.env" | cut -d= -f2- | tr -d "'\"")"
    if [[ -n "$compose_file" ]]; then
      set_env COMPOSE_FILE "${compose_file}:docker-compose.override.yml"
    fi
  fi

  if [[ -f "${SCRIPT_DIR}/fix-postfix-docker-relay.sh" ]]; then
    echo "==> Postfix docker relay"
    bash "${SCRIPT_DIR}/fix-postfix-docker-relay.sh"
  fi

  echo "==> Recreating GoTrue (auth) so SMTP env is picked up"
  cd "$SUPABASE_DIR"
  docker compose up -d --force-recreate auth
  sleep 5
  docker compose ps auth

  echo "==> SMTP connectivity from auth container"
  if docker compose exec -T auth sh -c "nc -zv -w 3 ${gotrue_host} ${SMTP_PORT}" 2>&1 | grep -qiE 'open|succeeded'; then
    echo "    OK: auth → ${gotrue_host}:${SMTP_PORT}"
  else
    echo "    WARN: auth cannot reach ${gotrue_host}:${SMTP_PORT}" >&2
    echo "    Use VPS mail relay instead: bash scripts/vps-hosting/setup-mail-relay.sh --remote" >&2
  fi

  echo "==> Done — test forgot password on https://wrl-dashboard.vercel.app/forgot-password"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  sync_gotrue_smtp
fi
